### ISSUE TITLE
from team marlbor-NO

### ISSUE THREAD

**Issue by jenyu7** [kkysen/r3d3#2]
Hi guys: 

Project looks pretty cool (and super cute!) However, we have the following questions: 
1. Where is your team roster? xdxd
2. Can there be a sliding bar so a user can directly slide through the months of the year? 
3. How is the world map going to work (your mockup only shows the US)? Also, it seems that if you tracked all the flights, the data on your chart will be extremely crowded. 
4. Are you marking major airports only, or all? How will this interaction happen? 
5. You should filter out your data, or have a menu option to filter out (e.g. checkboxes)

**Comment by kkysen** [comment]
Added to README
